<?php

namespace VehicleBundle\Repository;
use VehicleBundle\Entity\Make;

/**
 * MakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeRepository extends \Doctrine\ORM\EntityRepository
{

}
